* Outline
A witch doctor.
Practices herbalism.
Gives bad advice.
Interprets omens (Root Reading)
Tricks enemies (Figment)
Casts curses on her enemies.
Crafts potions (Magical crafting Feat 2).
Flies on a broomstick (Witch's Broom Feat 12).
Icky healing methods (Healing Plaster).
* Goblin, Mosquito Witch, Herbalist
** Ancestry: Goblin
Attributes: +Dexterity, +Charisma, +Free, -Wisdom
Languages: Common, Goblin, +INT more from list.
Darkvision.
** Heritage: Dokkaebi Goblin
Cast figment as an innate occult cantrip at will
Gain a +1 circumstance bonus to Will saves against illusions.
** Ancestry feat: Phantom Visage
A specific alternate form of a Small or Medium humanoid.
** Background: Herbalist
Attributes: +CON/WIS, +Free
Skills: Nature (T), Herbalism Lore (T).
Skill feat: Natural Medicine
** Class: Witch
Key attribute: INT
Trained in Perception
Saving Throws: Fortitude (T), Reflex (T), Will (E)
Skills: Patron skill (T), (3+INT extra) (T)
Attacks: simple weapons (T), unarmed attacks (T)
Defenses: Unarmored defense (T)
Trained in Witch class DC
Trained in spell attack modifier
Trained in spell DC
Attributes: +4 Free
Patron: Mosquito Witch
Familiar: Hawk
Spellcasting: Prepared
** Familiar
Animal: Hawk
Level: Same as mine
Perception: 3+Level (or INT+Level)
Acrobatics: 3+Level (or INT+Level)
Stealth: 3+Level (or INT+Level)
Other Skills: Level
HP: 5
Senses: Low light
Speed: 25
Pet abilities: (2 familiar, 2 witch)
  Patron ability (fixed, see below).
  Flier (fixed): Speed 25.
  Share Senses: Use familiar senses for 1m every 10m.
  Independent: 1 action if I don't command.
Spells: 10 C, 5 L1 + initial lesson
  Add 2 spells per extra level
  Can learn from scrolls or other witch's familiar.
** Hex spells
Spell 1: Patron's Puppet
** Patron: Mosquito Witch
Spell list: Primal
Patron skill: Nature
Hex cantrip: Buzzing bites (Cantrip 1)
  1 action, 1d4 damage, 30ft, 1 creature, 1 per creature per minute
  -> concealed (due to cast/sustain a hex)
Familiar learns: Pest form (Spell 1)
  Turn into a rat.
Swarm's Heart: Insect swarm provides concealment.
** Attributes
Goblin: +Dex, +Cha, +Int, -Wis
Witch: +Int
Free boosts: +Str, +Con, +Dex, +Int
Herbalist: +Con, +Int
Str +1  Dex +2  Con +2  Int +4  Wis -1  Cha +1
** Skills
Herbalist: Nature (T), Herbalism Lore (T).
Witch: Patron skill (T), (3+INT extra) (T)
Patron skill: Nature
  -> Performance
Extra skills:
  Arcana
  Crafting
  Deception
  Intimidation
  Occultism
  Stealth
  Survival
** Spells
*** Cantrips
Stabilize
Rousing Splash
Root Reading
Gouging Claw (2A, 2d6 slashing/piercing, 2 persistent bleed, touch)
Electric Arc (2A, 2d4 electric, 30 ft, 2 targets)
Slashing Gust (2A, 2d4 slashing, 1d4 persistent bleed, ranged)
Gale Blast (2A, 1d6 bludgeoning, pushed 5 ft, 5 ft emanation)
Know the Way (Navigation)
Draw Moisture
Glass Shield (1A, +1 AC)
Buzzing Bites (Hex - extra)
*** Normal
Mystic Armor (2A, +1 AC, all day)
Acidic Burst (2A, 2d6 acid, 5-foot emanation)
Pummeling Rubble (2A, 2d4 bludgeoning, 15 ft cone)
Pest Form (patron)
*** Focus
Patron's Puppet
** Equipment
Explorer's clothing (1 sp)
Dagger (2 sp)
Light mace (4 sp)
Sling with 20 bullets (nil)
Adventurer's pack (1 gp 5 sp)
  a backpack
  a bedroll
  10 pieces of chalk
  flint and steel
  50 feet of rope
  2 weeks' rations
  soap
  5 torches
  a waterskin.
Cookware (1 gp)
