* Session 1
We joined the expedition.  A few days in, one of the crawler tanks
started having trouble.  We got transferred to that tank to help the
mechanic.  We followed the other crawlers for some way, but then the
cliffs gave way above us.  A huge slab of rock fell down in front of
the crawler, the ground in front of us collapsed and the crawler fell
into a chasm.

Gunnar the mechanic had broken his leg.  I went to get a splint and
saw some yellow eyes looking in through the hatch.  It was a giant
centipede.  Snazzle tooth quickly killed it.  I splinted up the
mechanic's leg.  There was a lot of yelling and complaining, but I
managed to get it straightened out.  I don't know why people can't
hold still when you're trying to work on them.

We went outside the crawler and explored the cave.  We found a pile of
stones which seemed to be a column or statue.  On the far side of the
cave was another pile of stones, so we went to look at it, but some
more centipedes attacked.  We soon finished them off.  The pile of
stones looked like a door.

We found a narrow passage to some more caves.  We came to a fork in
the passage, and in one direction I spotted a red fungus which I
recognised as a shrieker.  I warned the others not to go that way, so
we explored the other.  There was a cascade of water which I
investigated.  In the bottom, I found a gem and the water seemed
magical.  I took a sip and it tasted like healing potion.  I put the
gem in my water skin.

At the end of the passage was a small chamber with some interesting
looking stones in.  There was a stone with some strange markings on.
Looking around, we could see another stuck under a flag stone.  I used
a crowbar to move a flag stone out of the way and got the stone out.

0 + 150 = 150 XP

* Session 2
Snazzle tooth fired an arrow at the shrieker and it started yelling.
Two mushrooms grew legs and ran towards us.  I cast Electric Arc at
the mushrooms.  One attacked Snazzle tooth with tentacles and she got
purple spores on her.  Then the other attacked Maggot.  I took the
blow badly and collapsed with the bludgeoning and poison damage.

Welly cast healing and brought me back.  We kept fighting and managed
to kill them, but we were badly hurt from it.

150 + 84 = 234 XP

We searched the fungus cave and found a length of fabric.

Gunnar had come around and was searching through crates.  He found
what the problem was with the crawler but said it would take time to
fix it.

We took a long rest before trying to get past the door.

Snazzle tooth tried to fit the runes into the door.  She placed the
blue rune stone into the door but it just dropped out again.  She put
the red one in and there was a click.  The door started to swing open
but got jammed on some rubble.  I heaved the stone out of the way and
it opened fully.

We walked down a long dark corridor which then opened out into a large
cavern.  There was a collapsed pillar in the middle and there were
various exits.

There was a patch of blue fungus, so I cast Electric Arc at it.
Nothing particular happened.  Just around the corner was a large
fungus shaped like a brain.  Snazzle started talking to herself.  She
said later that she had heard the voice of the fungus.

We turned back to the main cavern and tried a different passageway.
The end of it was blocked with a boulder which was covered in symbols.
I looked at them but they were jibberish.

Walker thought he saw some red lights flickering in the darkness.  We
went down the passage to investigate.  In the next cave were piles of
metal.

An ominous red light flooded the cave.  An armoured form rose from the
piles of metal and a fight broke out.

* Session 3
