* Session 1
We joined the expedition.  A few days in, one of the crawler tanks
started having trouble.  We got transferred to that tank to help the
mechanic.  We followed the other crawlers for some way, but then the
cliffs gave way above us.  A huge slab of rock fell down in front of
the crawler, the ground in front of us collapsed and the crawler fell
into a chasm.

Gunnar the mechanic had broken his leg.  I went to get a splint and
saw some yellow eyes looking in through the hatch.  It was a giant
centipede.  Snazzle tooth quickly killed it.  I splinted up the
mechanic's leg.  There was a lot of yelling and complaining, but I
managed to get it straightened out.  I don't know why people can't
hold still when you're trying to work on them.

We went outside the crawler and explored the cave.  We found a pile of
stones which seemed to be a column or statue.  On the far side of the
cave was another pile of stones, so we went to look at it, but some
more centipedes attacked.  We soon finished them off.  The pile of
stones looked like a door.

We found a narrow passage to some more caves.  We came to a fork in
the passage, and in one direction I spotted a red fungus which I
recognised as a shrieker.  I warned the others not to go that way, so
we explored the other.  There was a cascade of water which I
investigated.  In the bottom, I found a gem and the water seemed
magical.  I took a sip and it tasted like healing potion.  I put the
gem in my water skin.

At the end of the passage was a small chamber with some interesting
looking stones in.  There was a stone with some strange markings on.
Looking around, we could see another stuck under a flag stone.  I used
a crowbar to move a flag stone out of the way and got the stone out.

0 + 150 = 150 XP

* Session 2
Snazzle tooth fired an arrow at the shrieker and it started yelling.
Two mushrooms grew legs and ran towards us.  I cast Electric Arc at
the mushrooms.  One attacked Snazzle tooth with tentacles and she got
purple spores on her.  Then the other attacked Maggot.  I took the
blow badly and collapsed with the bludgeoning and poison damage.

Welly cast healing and brought me back.  We kept fighting and managed
to kill them, but we were badly hurt from it.

150 + 84 = 234 XP

(80 XP from somewhere: 314 XP)

We searched the fungus cave and found a length of fabric.

Gunnar had come around and was searching through crates.  He found
what the problem was with the crawler but said it would take time to
fix it.

We took a long rest before trying to get past the door.

Snazzle tooth tried to fit the runes into the door.  She placed the
blue rune stone into the door but it just dropped out again.  She put
the red one in and there was a click.  The door started to swing open
but got jammed on some rubble.  I heaved the stone out of the way and
it opened fully.

We walked down a long dark corridor which then opened out into a large
cavern.  There was a collapsed pillar in the middle and there were
various exits.

There was a patch of blue fungus, so I cast Electric Arc at it.
Nothing particular happened.  Just around the corner was a large
fungus shaped like a brain.  Snazzle started talking to herself.  She
said later that she had heard the voice of the fungus.

We turned back to the main cavern and tried a different passageway.
The end of it was blocked with a boulder which was covered in symbols.
I looked at them but they were jibberish.

Walker thought he saw some red lights flickering in the darkness.  We
went down the passage to investigate.  In the next cave were piles of
metal.

An ominous red light flooded the cave.  An armoured form rose from the
piles of metal and a fight broke out.

* Session 3
Welly threw water over the armour which stunned it.  Snazzle Tooth and
Walker started taking it apart.  It took them a little while, but they
managed it.

We explored the cave some more and found a door like the one before,
but this one was undamaged.

On the other side of the cave where there was a 20ft rock wall with a
statue on top.  We used a grappling hook and some rope to climb up.
We investigated the statue and Walker found a stone in its hand.

Beyond it was a 15ft drop followed by another wall.

I left the grappling hook and rope hanging and we went around the
other side to see if we could avoid crossing the drop.

Near the other side and down a side passage was a thick strong door
with a red glow coming from behind it.  I sent Talonface inside to
investigate.  Using shared sense, I saw some runes on the floor which
looked like it would transport creatures.  I instructed Talonface to
land on it and my shared sense was cut off.  We went into the room and
saw an outline of Talonface over the rune.

Snazzle Tooth managed to recover two rune stones from the floor.  I
then poked the outline of Talonface with my pole.  The rune flared up
and animated writing extended from the rune and attacked us.

A fight broke out, but we soon defeated the writing.  During the
fight, Snazzle Tooth picked up the outline of Talonface.  Next, I cast
a spell and Talonface returned to normal.

We returned to the door on the other side of the cave.  One of the
runes fit it and the door opened.  Behind it was a wall of ice with
bright light streaming through.  On the far side we could see figures
moving.

We jumped back as a flying creature sent a stream of flame at the ice.
Before long it had melted the ice and Mr Whispers greeted us.

314 + 230 = 544 XP

* Session 4
** At camp
We sold some of our loot.  We identified one of our items as a dancing
scarf.  I kept that for use.

I flew Talonface up high to have a look at the surrounding area.
  We are in a crater.
  To the South is the gorge.
  We have come down into a glacier.
  To the North, East and West there is ice for a long way.
  It is unbroken as far as the eye can see.

Snazzle Tooth found a crack which leads into the ice.  The passage
turns and stops abruptly at a sheet of ice which is nobbled and seems
thin but different from the rest of the ice.

Mr Whispers tapped on the ice and nothing happened.  He said that it
was enchanted and this way is closed for now.

** Exploring the passageway

Some of the NPCs were opening up another passageway into the ice.
They called us over.  We followed a passageway a short way and then it
forked.  Both ways seemed to be blocked.  Mr Whispers knocked on one
of the rocks and it split in two.

The next chamber was covered with broken masonry.  On the far side was
a knocked through wall with a square room beyond.  There were columns
supporting the ceiling and some strange devices.  On the far side of
the room were a couple of doors.  The stones seemed to be looking at
us.

While the others were milling around, we went through doors and they
closed behind us.  We heard giggling.  We found ourselves in a
corridor with doors on the other side.  We tried to open them but
failed.

Snazzle Tooth said "I don't suppose you could open these doors, could
you?"  We saw some strange creatures on the ceiling which we had been
interpreting as stones.  They spoke in a strange language which we
couldn't understand, but I used the dancing scarf and did a dance to
try to indicate that we wanted them to open the doors.  After a little
while, they did so.

** Ruined rooms

We went into the next room and saw a centipede in there, so we decided
to attack it.  We got into a fight and three others joined it.  We
managed to kill them without much difficulty.  We explored the room
and found two more sigil stones.

We also found a case containing 6 stoppered vials.  They were magic.

The next room was in disrepair and most things seemed broken.  I
wasn't looking where I was going and put my foot into a centipede
nest, but managed to get my leg our without them attacking.

To the North was a doorway with a corridor beyond, but we couldn't get
there because of the centipede nest.

** The mist room

We went back to an earlier corridor and explored to the North.  There
was a door with mist coming from its keyhole.  We opened the door and
Snazzle Tooth went in.  In the middle was a machine which was
whirling.

I went in and the mist seemed disorienting, so I told the others to
tie a rope onto the door handle so we could find our way out.

Snazzle Tooth jammed a crowbar into the machine.  There were some
sigil stones in there and we tried to get them out.  After several
attempts, we managed to get some sigils out of the machine.  Two of
the small stone creatures attacked us, but we ignored them.  When the
machine stopped, one of the stone creatures collapsed on the ground.

544 + 190 = 734XP

We followed a corridor and entered another room.

* Session 5

Our vision went blurry and we found ourselves in the entry hall again.
We saw some rune giants standing, looking at the doors.  The doors
burst open and some air elementals burst in.  The giants fired at the

Elves streamed in.  Stab the giants.

Rushing down the halls.

Enter a throne room.

Giant sitting on the throne.  Stands, picks up a hammer and swings it.

The giant is tough, but the elves are

Elf leaves their spear impaling the giant to the throne.  The elf
takes the crown of stone from the giant and lifts it.

We returned to our senses in slime and mess.  We are coated with green
goo and mushrooms growing out of it.

Walker jumped into the pool.  The water had a skin on it.  He had
spotted something and swam down to get it but returned empty handed.

I tied a rope around my waist, jumped in and swam down.  I managed to
get hold of a rune stone and brought it back up.

I cast detect magic.  There was a general suffusion of magic over the
fungus.  The fungus seems to weave a web of illusion by sending spores
into the air.

I cleared an area of the pool and it seemed that the bottom was further down.

We searched the room and found two more rune stones.

We went further down the corridor and Snazzle pushed a door open.

** Throne room

On the throne was a large skeleton with a silver spear protruding from
its chest.  There were cobwebs all over the room.  I crept towards the
throne and a large spider dropped on me from the ceiling.

It spun a web around me and carried me up towards the ceiling.
Suddenly I was falling and snazzle poured some healing potion into my
mouth.  I healed myself and cast clinging ice at the spider.

Walker and Welly were fighting another spider.  It was a tough fight,
but we managed to defeat both spiders.

I took the spear from the chest of the giant.  I threw it at the
spider corpse and it pierced the armor easily.  It then glowed for a
moment, disappeared and reappeared in my hand.  It was inscribed with
runes of potency and returning.

There was a banner when we entered the room, but it got set of fire
during the fight.  The banner staff had runes on it.  I sensed that it
was one of a pair.

Staff of protection.  Shield, Alarm, Mystic Armor.

** Dusty cave

We went along a corridor to the north of the fog room.  The walls were
partly collapsed.  We found ourselves in a dusty cave with bones
scattered around.  We heard a buzzing or humming sound.

We found a crawler with number 115 on it.

734XP + 240XP = 974XP

* Session 6
** Dusty cave

We fought the skeltons and defeated them.

Beyond was the crawler which was buzzing with electricity.  Snazzle
jumped up in through the hatch and threw some rubber tracks out to let
us get up without getting shocked.

The Ethereum core was exposed which looked dangerous.

There was a box was made of heart wood with a picture of a rook with a
lightning strike.  That's the symbol of the bleak tower.  We suspect
the skeletons were the original crew of the 115.

On the front of the crawler was a drill head, which Snazzle removed.

974XP + 140XP + 80XP = 1194XP

* Session 7

We found lots of junk in the crawler.  We decided to go back to camp.

When we approached the locked door, there was a loud bang and pieces
of the door fell off before the whole thing gave way.  Reginald Doyen
appeared with a rigged up jack hammer.  We told him about what we'd
found and he said that we have earned a rest.  He went to recover
supplies.  He said the drill might be our way out of here.

In the hall, some people had mostly put together one of the devices
and were trying to work out how it worked.

We asked Lirion about the locked box, and he said he didn't know
anything about it.  As we were moving on, he mentioned that he had
found a related object.  He handed us something which looked like a
pen, which had the same symbol on it.  On closer examination, it
wasn't a pen, but an engraved stone.  We tried it in the key hole of
the box.  It fit, but didn't open the box.

We went to talk to Selene.  She told us that the crew were a creepy
lot.  There were wizards from bleak tower.  There were 18-20 of them.

Mr Whispers was kneeling near the south side of the crater.  He was
not moving and barely breathing.  He was surrounded by some stones on
small legs which were gently swaying.

I got ingredients for 6 healing potions.  I set up equipment for
brewing them.

The scouts returned from the gorge and said there was no way out up
there.

Selene got the box open.  She showed us the box and the tools she
used.  There were three indentations inside with three wands inside.

We had a night's rest.  I brewed a temporary healing potion.

Reginald directed us to explore the cave more.  We followed an icy
passageway and it opened out into a large chamber with multiple
levels.  A beam of light came from above and lit a creature which was
lying on the ice.

As we made our way to it, we noticed some body parts in the ice.  A
disembodied handle jumped up in front of Snazzle and skurried away.
Then others which had been hidden crawled up out of the snow.

They attacked us, so we fought back.  In the fight the creature, which
turned out to be a polar bear, joined us in the fight.  It seemed to
have an affinity to Walker.

* Session 8

We continued fighting the hands and defeated them.

194XP + 130XP = 324XP

We climbed down the sides of a hole.  Snazzle got to the bottom first
and snatched a blue rune stone from some bone fingers which were
holding it.  Suddenly, the bottom of the hole collapse revealing a
giant hand.  It started thrashing about as we climbed back up the rope.

We Escaping the giant hand

324XP + 60XP = 384XP

We went down some icy passages.  Snazzle found a skull in an alcove
and threw it to me.  It had 8 teeth with runes inscribed which I took.
Snazzle lit a torch and a spider skittered away.

We continued and found a wall made of hands.  I shot a caustic blast
at it and they attacked us.  After a short while, we defeated them.

384XP + 80XP = 464XP

We continued a long way down and found drop down.  Snazzle went into a
cave and found a skelton with a wand and backpack.  It had 80 gold
which we distributed.

464XP + 30XP = 494XP

* Session 9

We explored one passage which seemed to take us back to the crater
with the camp in, but there was a barrier which prevented us from
getting out that way.

We went back to the chasm and snazzle jumped across, or at least tried
to.  She used a pole to get more height but it slipped and she ended
up falling down and landed on a ledge below the top of the chasm.

I jumped across without problem.  I tied a rope around me, dropped
down the far side and threw the rope over to snazzle.

For crossing the chasm:
  494XP + 80XP = 574XP

There were some marks in the rock which looked like writing, but it
turned out they were just cracks.

We followed a passageway and ended up in a large cave with rocks and
snow.  We went a small way into the cave and suddenly some hands
jumped up out of the snow and grabbed me.

The rocks kept sinking into the snow and hands kept jumping out.  We
struggled and eventually made our way across.

For crossing the cave:
  574XP + 80XP = 654XP

We followed another passageway and it opened out into another cave
which seems to be a dead end.  In the middle was a strange spherical
device.

After an hour of studying it, I figured out it had these controls:
  Slider: Cold->Hot
  Slider: Calm->Stormy
  Buttons: Water, light, life, warmth

I turned the temperature up part of the way and the machine started to
judder and shake.

I pressed the warmth button which lit up and then went out.

I moved the stormy slider to calm and it went part way and got stuck.
Snazzle used a tool to extract a rock from the slider.  I slid the
slider to calm and the machine made noises for a bit and then
everything went very quiet.

I pressed the light button.  It flickered a bit, but didn't seem to
turn on.

I investigated the things we found on the wizard's body.  It had a
staff, broken wand, note book brass with a clasp lock, mostly blank
tablet made out of stone with a runic inscription around the edge.

When I pressed the metal rod which Lirion had found against the
tablet, a white dot appeared and then disappeared after a moment.  I
then drew a circle, which then disappeared after a moment.  Then some
words appeared in common: Who are you and how did you get the slate?
I tried to write a response, but it didn't seem to work.  I concluded
that it needed time to recharge.

Snazzle opened the note book by breaking the clasp off.  It turned out
to be a journal and one of the entries seemed to be talking about the
machine:

  The control sequence should be: Storm-rune to neutral position, then
  Cold-bringer to minimal setting, then activate the warming glyphs in
  sequence: Sun, Thaw, Spring-water, Growth. At least I think so. The
  translation is... difficult. My head won't stay clear.

I think:
  Sun=light
  Thaw=Warmth
  Spring-water=water
  Growth=life
